### ISSUE TITLE
Repositórios separados / +1 Collaborator

### ISSUE THREAD

**Issue by gustavo-oliveira-rosa** [RuanNunes/find-cnpj#1]
O que acha de separar esse repositório em 2?
Um para a rotina de população de banco e outro para a API em si?

Obs: Separar por organização e frescuragem // Separar por estar sendo usado repositórios diferentes com linguagens diferentes com objetivos diferentes mesmo que se converjam.

E se possivel, me coloque como colaborador. Gostaria de participar desse projeto! :)

**Comment by RuanNunes** [comment]
claro, sem problemas, optei por fazer no mesmo repo por ser mais simples inicialmente.

**Comment by gustavo-oliveira-rosa** [comment]
Ok! Feshow!
Vamos trabalhar.
